### ISSUE TITLE
No images found in album

### ISSUE THREAD

**Issue by dgndgn** [andsala/unsee-dl#13]
unsee-dl not working - I get `No images found in album` for all downloadable albums.

I guess, unsee changed something 

Anyone facing similar issue?

**Comment by dgndgn** [comment]
[this patch](https://gist.github.com/dgndgn/0a2d3a27bee89e19957d2d494b018149) worked for me

**Comment by anoduck** [comment]
Nice work @dgndgn! Thank you, Sir! I had fixed the urls, but was completely at a loss for how to get aiohttp to use a valid url. Will commit the changes to my branch and submit a pull request.
