### ISSUE TITLE
KeyError: 'data' -- failing only on unsee Beta

### ISSUE THREAD

**Issue by anoduck** [andsala/unsee-dl#16]
I am assuming that this Morning unsee apparently changed it's graphql scheme. Because where it worked up until 5am last night, it no longer does. Noe the following error is generated.

```python
Traceback (most recent call last):
  File "/unsee-dl/main.py", line 104, in <module>
    main()
  File "/unsee-dl/main.py", line 14, in main
    asyncio.get_event_loop().run_until_complete(run_downloader())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/unsee-dl/main.py", line 98, in run_downloader
    await download_beta(album_ids_beta_version, args.out_dir, args.group_album)
  File "/unsee-dl/main.py", line 33, in download_beta
    await client.anonymous_login()
  File "/unsee-dl/unsee_dl/unsee_beta.py", line 62, in anonymous_login
    tokens = content["data"]["getToken"]
KeyError: 'data
```

I am comfortable making minor corrections, and understand the basics of what a key error is. As for going about troubleshooting this error, I am completely lost.

https://stackoverflow.com/questions/66306834/pythongraphql-keyerror-data-received-response-from-websocket-server-change

**Comment by dgndgn** [comment]
Looks like the graphql is screwed up
```
'errors': [{'message': 'Cannot query field "getToken" on type "Query".', 'locations': [{'line': 3, 'column': 3}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Unknown type "AuthPayload". Did you mean "Upload"?', 'locations': [{'line': 9, 'column': 33}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}]}
```

**Comment by anoduck** [comment]
@dgndgn I appreciate some feedback. Admittedly I am over my pay grade, but nonetheless have spent numerous hours attempting to learn and troubleshoot what little I can, and I have gotten nowhere. 

I discovered the server running the websocket server on unsee.cc is apollo graphql. You can connect to the websocket and query the server if you can find the appropriate syntax to do so, which I have not. It is not the standard graphql syntax, but rather a json based variant. 

I have installed a test server locally to test queries with, but the syntax is different than on the websocket, and I am having some difficulty locating documentation relating to the json variant. According to what I am reading, the following should be an appropriate introspection query that would inform the user on types available should look like this:

```graphql
{

  __schema {

    directives {

      name

      description

    }

    subscriptionType {

      name

      description

    }

    types {

      name

      description

    }

    queryType {

      name

      description

    }

    mutationType {

      name

      description

    }

    queryType {

      name

      description

    }

  }

}
```

But as you can tell, the above query is not in json format, and converting it to such has not proved to be fruitful. So as for the moment, I am just spinning my wheels and not getting anywhere. It has been one hellacious week. I think I need to take a nap, now.

Below are a few links with good reference information in them:  
https://www.apollographql.com/blog/the-anatomy-of-a-graphql-query-6dffa9e9e747/  
https://graphqlmastery.com/blog/graphql-introspection-and-introspection-queries

**Comment by anoduck** [comment]
I never really appreciated how advanced this python script was until I started to take a nose dive into resolving this error.

**Comment by anoduck** [comment]
@andsala As usual, thank you for all the work you have done. I will find some way to repay you, I swear.
