### ISSUE TITLE
Script is currently broken. Reports 0 images in album, and downloads nothing. No errors given.

### ISSUE THREAD

**Issue by anoduck** [andsala/unsee-dl#19]
Script no longer works on both old unsee and new unsee. Does not output album id as it use to, it reports there are 0 images in album, downloads nothing, and no errors are given.

**Comment by anoduck** [comment]
@dgndgn Have you tested out the new release? Are you getting the same errors? Have any clue what is going on?

**Comment by dgndgn** [comment]
@anoduck , use `url` instead of room id

**Comment by anoduck** [comment]
@dgndgn I feel like a complete idiot now. 
Do you know how much time I have spent working on finding a solution? How I started my studies in python all over again? How many late nights I stayed awake? Jeezus, FML... But, at least it works.
