### ISSUE TITLE
Only downloads the first image.

### ISSUE THREAD

**Issue by anoduck** [andsala/unsee-dl#2]
When using your most awesome app, I noticed that it only downloads the first image of every gallery. It does not download any other image but the first. Is there a reason why this is happening?

**Comment by andsala** [comment]
When I started working on this, galleries were not in the roadmap.
I'll try to work on that when I have more time otherwise I'm happy to accept PR.

**Comment by anoduck** [comment]
I have a feeling, I am going to regret asking this. But, what do you mean "PR"? For me, "PR" still refers to "Public Relations" or "Private Recommendations". I guess you mean "Private Revisions"?

**Comment by anoduck** [comment]
Holy crap! You released another version. Wow, that is awesome! Thank you!

**Comment by andsala** [comment]
Yes, I ended up digging into your issue and rewrote the entire script.

PR means [Pull Request](https://help.github.com/en/articles/about-pull-requests), it's the way you contribute to a project.

**Comment by anoduck** [comment]
You are so Awesome! Thanks again!
