### ISSUE TITLE
Unsee Beta released

### ISSUE THREAD

**Issue by anoduck** [andsala/unsee-dl#5]
I so appreciate you writing this script, use it daily actually.

There is now unsee Beta which uses a sixteen digit identifier rather than an eight digit. Are there any plans to support the new version of unsee?

**Comment by andsala** [comment]
I gave it a quick look and it looks interesting, I will try to work on it in the coming days.

**Comment by anoduck** [comment]
Dude, you are so much getting a Christmas card from me this year. Thanks a million.
